Isolated scatter-gather scripts from version 1.1

diff --git a/scripts/globals.sh.template b/scripts/globals.sh.template
--- a/scripts/globals.sh.template
+++ b/scripts/globals.sh.template
@@ -1,14 +1,17 @@
 # Modify the following paths accordingly
-input_dir=
 output_dir=$(pwd)
 tools_dir=
+tmp_dir[1]=
+tmp_dir[2]=
 
-bam_dir=$output_dir/bam
-rpt_dir=$output_dir/rpt
-vcf_dir=$output_dir/vcf
+ref_dir=
+fastq_dir=
+sam_dir=
+bam_dir=
+log_dir=
 
 # Reference Genome Info
-ref_genome=$ref_dir/human_g1k_v37.fasta
+ref_genome=$ref_dir/factor4/human_g1k_v37.fasta
 db138_SNPs=$ref_dir/dbsnp_138.b37.vcf
 g1000_indels=$ref_dir/1000G_phase1.indels.b37.vcf
 g1000_gold_standard_indels=$ref_dir/Mills_and_1000G_gold_standard.indels.b37.vcf
@@ -16,8 +19,9 @@ g1000_gold_standard_indels=$ref_dir/Mills_and_1000G_gold_standard.indels.b37.vcf
 # Tools
 BWA=
 SAMTOOLS=
-GATK=
 PICARD=
+GATK=
+GATK_QUEUE=
 JAVA=
 
 check_input() {
@@ -31,8 +35,17 @@ check_input() {
 check_output() {
   filename=$1;
   if [ -f $filename ]; then
-    echo "Output file $filename already exists";
-    exit 1;
+    echo -e "Output file $filename already exists,do you want to run again to cover it? \e[31m[yes|no]\e[0m"
+    read answer
+    if [ $answer == "yes" ];then
+      echo "Continue to cover the $filename"
+    elif [ $answer == "no" ];then
+      echo "Exiting,choose another file name if it's necessary"
+      exit 1;
+    else 
+      echo "Please type yes or no"
+      check_output $filename
+    fi
   fi;
   # Check if output folder writtable
   echo "1" > $filename;
@@ -41,6 +54,22 @@ check_output() {
     exit 1;
   fi;
   rm $filename;
+}
+
+
+# check if output dir exists and is writable
+check_output_dir() {
+  dir=$1;
+  if [[ ! -d "$dir" ]]; then
+    echo "Output dir $dir does not exists";
+    exit 1;
+  fi;
+  echo "1" > $dir/.test;
+  if [ ! -f $dir/.test ]; then
+    echo "Cannot write to folder $dir";
+    exit 1;
+  fi;
+  rm $dir/.test;
 }
 
 # create output dir if it does not exist 
@@ -53,4 +82,29 @@ create_dir() {
       exit 1;
     fi
   fi;
+}
+
+# log messge
+log_msg() {
+  local level=$1;
+  local msg=$2;
+  local v=$verbose;
+  if [[ "$v" == "" ]]; then
+    local v=1;
+  fi;
+  if [ "$level" -le "$v" ]; then
+    (>&2 echo "$msg");
+  fi;
+}
+
+log_info() {
+  log_msg 2 "$1";
+}
+
+log_warn() {
+  log_msg 1 "$1";
+}
+
+log_error() {
+  log_msg 0 "$1";
 }
