Modified according to scale-out version of BWA, merging sort and align into a single stage

diff --git a/scripts/globals.sh.template b/scripts/globals.sh.template
--- a/scripts/globals.sh.template
+++ b/scripts/globals.sh.template
@@ -1,16 +1,15 @@
 # Modify the following paths accordingly
-output_dir=$(pwd)
-input_dir=/pool/hdd1/diwu
-tools_dir=/fcs_common/merlin1/tools
+output_dir=
+input_dir=
+tools_dir=
 
-# Directories setup
-fastq_dir=$input_dir/fastq
-ref_dir=/space/scratch/genome/ref
-sam_dir=$output_dir/sam
-bam_dir=$output_dir/bam
-rpt_dir=$output_dir/rpt
-vcf_dir=$output_dir/vcf
-log_dir=$output_dir/log
+fastq_dir=
+ref_dir=
+sam_dir=
+bam_dir=
+rpt_dir=
+vcf_dir=
+log_dir=
 
 # Reference Genome Info
 ref_genome=$ref_dir/factor4/human_g1k_v37.fasta
@@ -19,14 +18,12 @@ g1000_indels=$ref_dir/1000G_phase1.indels.b37.vcf
 g1000_gold_standard_indels=$ref_dir/Mills_and_1000G_gold_standard.indels.b37.vcf
 
 # Tools
-#BWA=/curr/diwu/prog/bwa-flow/bin/run-bwa.sh
-BWA=$tools_dir/bwa-fcs/bwa
-SAMTOOLS=$tools_dir/fcs-samtools
-PICARD=$tools_dir/fcs-picard.jar
-GATK=$tools_dir/gatk-3.5/GenomeAnalysisTK.jar
-#GATK_QUEUE=$tools_dir/gatk-3.5/Queue.jar
-GATK_QUEUE=$tools_dir/fcs-gatk/Queue.jar
-JAVA=/curr/diwu/tools/jdk1.7.0_80/bin/java
+BWA=
+SAMTOOLS=
+PICARD=
+GATK=
+GATK_QUEUE=
+JAVA=
 
 check_input() {
   filename=$1;
@@ -49,4 +46,31 @@ check_output() {
     exit 1;
   fi;
   rm $filename;
+}
+
+# check if output dir exists and is writable
+check_output_dir() {
+  dir=$1;
+  if [[ ! -d "$dir" ]]; then
+    echo "Output dir $dir does not exists";
+    exit 1;
+  fi;
+  echo "1" > $dir/.test;
+  if [ ! -f $dir/.test ]; then
+    echo "Cannot write to folder $dir";
+    exit 1;
+  fi;
+  rm $dir/.test;
+}
+
+# create output dir if it does not exist 
+create_dir() {
+  dir=$1
+  if [[ ! -d "dir" ]]; then
+    mkdir $dir &> /dev/null;
+    if [ $? -ne 0 ]; then
+      echo "Cannot create dir $dir";
+      exit 1;
+    fi
+  fi;
 }
